baseURL = 'https://267859.github.io/267859_ZPC_2025/'
languageCode = 'en-us'
title = 'ZPC 2025 Tomáš Krompaský'
theme = "gokarna"

[params]
  avatarURL = "/267859_ZPC_2025/images/avatar.png" # profile image on homepage
  ShowPostsOnHomePage = "recent"    # or false if you don’t want posts listed
  numberOfPostsOnHomePage = 4
[markup.goldmark.renderer]
  unsafe = true